### PR TITLE
Added sqrt function

### LINKED ISSUE #6: Add Square Root Function

### PR DESCRIPTION
**Pull request by pixobia**
resolved #6

### CODE REVIEW

**Comment by Prasanta-Hembram** [comment]
Great @pixobia can you also make changes to asm folder too.

**Comment by pixobia** [comment]
OK sureee

**Comment by pixobia** [comment]
Hi bro done changes ,crated pull request,please merge the two pull request
of issue #11 and #6,then I could make changes on css as well...

**Comment by Prasanta-Hembram** [comment]
Thanks you so much @pixobia

**Comment by pixobia** [comment]
Css files have been linked hope u will merge them..

**Pull request merged**
